const mongoose = require('mongoose'),
      Schema = mongoose.Schema;

// Schema defines how chat messages will be stored in MongoDB
const ConversationSchema = new Schema({
  participants: [{ type: Schema.Types.ObjectId, ref: 'User'}],
});

module.exports = mongoose.model('Conversation', ConversationSchema);

/*
RPT NOTES:

Our conversation schema will essentially just hold the participants of the
conversation and generate an ID for the conversation. We are specifying that
our participants field will contain an array of IDs generated by MongoDB. The
'ref' you see is setting up a Mongoose populate, which sort of simulates a join
from MySQL, if you're familiar with that.  There are no real joins in MongoDB.
*/
